language: python
python:
- '3.4'
before_install:
- chmod +x tools/build.sh
- pip install sqflint  
before_script:
- sudo apt-get install realpath
- mkdir -p tools
- export RAW_VERSION=$(git describe --always --tag)
script:
- tools/build.sh
- tools/preprocess.sh
- for SQFFILE in `find . -iname '*.sqf'`; do sed -i -E 's/^#.*//g' "$SQFFILE"; done # remove hash comments, they confuse the hell out of sqflint
- sqflint -d . -ee
notifications:
  slack: gruppe-adler:WUbRswFJEqy55XKuLhtXTlOf
  template:
  - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
  - 'Commit Title : %{commit_subject}'
  - 'Commit details : %{commit_message}'
deploy:
  provider: releases
  api_key:
    secure: O7V4jaO95Jls8fbvfd/uAb11PWrYlnyiCCnki8a+aB1BJfVPxAhAY1xh+uQRUDY2YEGK4fPDTdDs6KPNyaekXCNtFV4d+zShEvaD9EZPYtLuHHFk/nUG8yZx9rJdqrWEHL2QGxFC8O2jmTPzfF9W0mGZctRx1U86ca/rHyYKTUHZMInWLv9TAxd9zynLUJ6eZprTMwW9LacdMBeQwHke0aJXRnPn9Z7768xwLBQm0c1XDGdbDVeOswZZ2ID3QeoTWPLneZk24UsQFzLRKeR9Bq4sAWPU9ATpGW9kvABgXKyC/ftK60Vm7dqgb8ckXR7H5E0D+lMAEUDt0KxkoyKdQA5Gijz21K9s9/945P2FAAvR9WDGpnzc89XyAhnT6KshEY67RVyLroSa9zbVq7zLtq7jGK7JeL0xLwzraTkhx3Tbxxikd4g4fphZV/09PTMjQ26KGBnMx+60Yg9Hwj6yTB78QGmytEhVjfn4GfzraBDwaVkLoMRlvxDlE2l/heKno/Hmg5Etiywcng5u2j5bHRpitat3bHapWGblk9H1Cky3qO4LVPRvnZ6HjIggw+B26hq/XCP8p8f+B2cufORHfZWLHAObzQmd4lWbqow42VRyTb1NZ5QAQ5Mj7GeHZQlorCfp9am9O7XMwsTSqVsR/GKr1WWbGtNjbR6UXu6l4k0=
  file: release/@gruppe_adler_mod-$RAW_VERSION.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
