language: python
python:
- '3.4'
before_script:
- mkdir -p tools
- wget http://gruppe-adler.de/api/travis/sqf_validator.py
- sed -i -e 's/addons//g' sqf_validator.py
- mv sqf_validator.py tools/
script:
- python3 tools/sqf_validator.py
notifications:
  slack: gruppe-adler:WUbRswFJEqy55XKuLhtXTlOf
  template:
  - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
  - "Commit Title : %{commit_subject}"
  - "Commit details : %{commit_message}"
