name = "Gruppe Adler Mod"
prefix = "grad"
author = "Gruppe Adler"
files = [
    "Adler.paa",
    "Adler_w.paa",
    "Adler_64.paa",
    "Adler_w_64.paa",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
include = [
    "./include"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip gruppe_adler_mod_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
